### ISSUE TITLE
where to find 'Data/kenya_sites_2.csv' file?

### ISSUE THREAD

**Issue by liamxg** [SindisoNyathi/doctoralrepo_dengue_phylo#3]
Dear @SindisoNyathi,

Could I know where to find 'Data/kenya_sites_2.csv' file?
Thanks.

Best,
Liam

**Comment by SindisoNyathi** [comment]
I have attached it here.

Please note that these location coordinates were modified (shifted up or
down) so the transition arrows in Supp. Figure 5 in the figure would be
visible. Actual locations might be slightly different.

Sindiso.

**Comment by SindisoNyathi** [comment]
[kenya_sites_2.csv](https://github.com/user-attachments/files/17619565/kenya_sites_2.csv)

Dear Liam,

What about now. 

Sindiso.
